config/routes.rb
Rails.application.routes.draw do
  root to: "movies#index"
  resources :movies, only: [:index, :show]

  resources :lists, only: [:index, :show, :new, :create, :destroy] do
    resources :bookmarks, only: [:new, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list

  validates :comment, length: { minimum: 6 }
  validates :movie, presence: true
  validates :list, presence: true
  validates :movie_id, uniqueness: { scope: :list_id, message: "has already been bookmarked" }
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, presence: true, uniqueness: true
  validates :overview, presence: true

  before_destroy :ensure_no_bookmarks

  private

  def ensure_no_bookmarks
    return false if bookmarks.exists?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: [:new, :create]
  before_action :set_bookmark, only: [:destroy]

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @list = List.find(params[:list_id])
    @bookmark = @list.bookmarks.build(bookmark_params)

    if @bookmark.save
      redirect_to list_path(@list), notice: 'Bookmark added successfully.'
    else
      render :new
    end
  end

  def destroy
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), notice: 'Bookmark was successfully deleted.'
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:movie_id, :comment)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]

  # app/controllers/lists_controller.rb

def index
  # Load lists and preload the first movie of each list.
  @lists_with_movies = List.left_joins(bookmarks: :movie)
                          .select('lists.id AS list_id, lists.name AS list_name, movies.poster_url, movies.id AS movie_id')
                          .group('lists.id, movies.id')
                          .order('lists.id, movies.id')
end


  def show
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to @list, notice: 'List was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @list = List.find(params[:id])
    @list.destroy
    redirect_to lists_path, notice: 'List was successfully deleted.'
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name)
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/bookmarks/new.html.erb
<div class="container">
  <div class="bookmarks-create d-flex flex-column p-2">
    <%= simple_form_for [@list, @bookmark] do |f| %>
    <%= f.association :movie %>
    <%= f.input :comment, placeholder: "Add your comment here..." %>
    <%= f.button :submit, class: "link-button" %>
    <% end %>
    <%= link_to 'Back', list_path(@list), class: "link-edit" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="container">
  <div class="d-flex justify-content-center mt-5">
      <%= link_to 'Back to Movies', movies_path, class: "link-button me-3" %>
      <%= link_to 'New List', new_list_path, class: "link-button" %>
  </div>

  <%# Grid start %>
  <div class="row">
    <%# Iteration start %>
    <% @lists_with_movies.each do |list_with_movie| %>
      <div class="card col-2 p-3 m-3 list-card card-hover-black" style="width: 18rem;">
        <% if list_with_movie.movie_id %>
          <img src="<%= list_with_movie.poster_url %>" class="card-img-top" alt="...">
        <% else %>
          <img src="" alt="">
        <% end %>

        <div class="card-body">
          <h2 class="card-title"><%= link_to list_with_movie.list_name, list_path(list_with_movie.list_id), class: "link-edit" %></h2>
          <p class="card-text">Some quick example</p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/lists/new.html.erb
<div class="container">
  <div class="d-flex flex-column align-items-center p-5 list-form-create card-hover-blue">

    <h1 id="new-list-create-page">New List</h1>
    <%= simple_form_for @list do |f| %>
      <div class="d-flex flex-column">
        <%= f.input :name, label: 'Name' %>
        <%= f.button :submit, class: "link-button"%>
      </div>
    <% end %>
    <%= link_to 'Back', lists_path, class: "link-edit" %>

  </div>
</div>

app/views/lists/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <%# List Name %>
      <div class="d-flex flex-column align-items-center mb-4">
        <h1><%= @list.name %></h1>
        <%= link_to 'Add Bookmark', new_list_bookmark_path(@list), class: "link-button mt-2" %>
      </div>
      <%# Card Bookmarks %>
      <div class="card mb-4 bookmarks-show-card">
        <div class="card-body">
          <h2 class="border-bottom mb-3">Bookmarks</h2>
          <%# Condition for bookmarks %>
          <% if @list.bookmarks.any? %>
            <ul class="list-group list-group-flush">
              <% @list.bookmarks.each do |bookmark| %>
                <li class="list-group-item">
                  <div class="d-flex align-items-center justify-content-between">
                    <%= bookmark.movie.title %>
                    <%= link_to bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Are you sure you want to delete this bookmark?" } do %>
                      <i class="fas fa-trash-alt delete-icon"></i>
                    <% end %>
                  </div>
                  <p class="mt-2"><%= bookmark.comment %></p>
                </li>
              <% end %>
            </ul>
          <% else %>
            <p>No bookmarks yet!</p>
          <% end %>
        </div>

      </div>
      <%= link_to 'Back', lists_path, class: "link-edit" %>

    </div>
  </div>
</div>

app/views/movies/index.html.erb
<div class="container d-flex flex-column ">


  <div class="movie-cards-grid row gap-5">
  <div class="d-flex flex-sm-column align-items-start">
    <h1 class="mt-3 mb-3 pe-3">Movies</h1>
    <%= link_to 'View All Lists', lists_path, class: "link-button" %>
  </div>
      <% @movies.each do |movie| %>
        <div class="card card-hover-black p-1 col-md-5 align-items-center" id="movie-card" style="width: 18rem;">
          <img class="card-img-top" src="<%= movie.poster_url %>" alt="movie">
          <div class="card-body">
            <h5 class="card-title"><%= movie.title %></h5>
            <p class="card-text"><%= movie.overview %></p>
          </div>
          <ul class="list-group list-group-flush" id="ratings-movies-display">
            <li class="list-group-item">Ratings: <%= movie.rating %></li>
          </ul>
          <div class="card-body show-text-movie">
            <%= link_to 'Explore', movie_path(movie), class: "link-edit", id: "explore-movies-display"%>
          </div>
        </div>
      <% end %>
  </div>

</div>

app/views/movies/show.html.erb
<div class="container">
  <div class="d-flex flex-column align-items-center mt-5">
    <div class="card card-hover-black mb-3" style="max-width: 540px;">
      <div class="row g-0">
        <div class="col-md-4 p-3">
          <img src="<%= @movie.poster_url %>" class="img-fluid rounded-start" alt="Movie">
        </div>
        <div class="col-md-8">
          <div class="card-body p-3">
            <h5 class="card-title"><%= @movie.title %></h5>
            <p class="card-text"><%= @movie.overview %></p>
            <p class="card-text"><small class="text-body-secondary">Last updated 3 mins ago</small></p>
            <p><small class="text-muted"><strong>Rating:</strong> <%= @movie.rating %></small></p>
            <%= link_to 'Back to Movies', movies_path, class: "link-button" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>